import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ScreenHeader } from '../components/ui';
import { useTheme } from '../context/ThemeContext';
import { getVerificationRevenue } from '../services/employeeAuthService';

export default function AdminVerificationRevenueScreen() {
  const { colors } = useTheme(); const [data,setData]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{setData(await getVerificationRevenue());setError('');}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const max=useMemo(()=>Math.max(1,...(data?.trend||[]).map(x=>Math.max(x.successful,x.failed))),[data]);
  return <View style={[s.root,{backgroundColor:colors.background}]}><ScreenHeader title="Миний орлого" subtitle="verify.mn · баталгаажуулалт бүр 40₮" back/><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.content}>
    {loading&&!data?<ActivityIndicator color={colors.primary}/>:<><View style={s.grid}><View style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[s.label,{color:colors.textMuted}]}>Нийт орлого</Text><Text style={[s.value,{color:colors.success}]}>{Number(data?.revenueMnt||0).toLocaleString()}₮</Text><Text style={{color:(data?.change||0)>=0?colors.success:colors.danger}}>{(data?.change||0)>=0?'Өссөн':'Буурсан'}: {Math.abs(data?.change||0)*40}₮</Text></View><View style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[s.label,{color:colors.textMuted}]}>Амжилттай / Амжилтгүй</Text><Text style={[s.smallValue,{color:colors.success}]}>{data?.successful||0} / <Text style={{color:colors.danger}}>{data?.failed||0}</Text></Text></View></View>
    <View style={[s.chartCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[s.chartTitle,{color:colors.text}]}>Сүүлийн 7 өдөр</Text><View style={s.chart}>{(data?.trend||[]).map((x)=><View key={x.date} style={s.day}><View style={s.bars}><View style={[s.bar,{height:Math.max(3,x.successful/max*110),backgroundColor:colors.success}]}/><View style={[s.bar,{height:Math.max(3,x.failed/max*110),backgroundColor:colors.danger}]}/></View><Text style={[s.dayText,{color:colors.textFaint}]}>{x.date.slice(8)}</Text></View>)}</View><View style={s.legend}><Text style={{color:colors.success}}>● Амжилттай</Text><Text style={{color:colors.danger}}>● Амжилтгүй</Text></View></View>
    <View style={[s.warning,{backgroundColor:colors.danger+'18',borderColor:colors.danger}]}><Text style={[s.warningText,{color:colors.danger}]}>Нэгж дууссан байж магадгүй</Text></View></>}
    {!!error&&<Text style={{color:colors.danger,marginTop:20}}>{error}</Text>}
  </ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1},content:{padding:18},grid:{flexDirection:'row',gap:12},card:{flex:1,borderWidth:1,borderRadius:18,padding:16,minHeight:140},label:{fontSize:13,fontWeight:'700'},value:{fontSize:29,fontWeight:'900',marginVertical:17},smallValue:{fontSize:25,fontWeight:'900',marginTop:27},chartCard:{borderWidth:1,borderRadius:18,padding:18,marginTop:14},chartTitle:{fontSize:17,fontWeight:'800'},chart:{height:145,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around',marginTop:12},day:{alignItems:'center',flex:1},bars:{height:115,flexDirection:'row',alignItems:'flex-end',gap:3},bar:{width:9,borderRadius:4},dayText:{fontSize:11,marginTop:6},legend:{flexDirection:'row',justifyContent:'center',gap:20,marginTop:10},warning:{borderWidth:1,borderRadius:14,padding:15,marginTop:14},warningText:{fontWeight:'800',textAlign:'center'}});
